"""
ui/app.py
----------
The Streamlit front-end for FounderGPT.

Run it from the foundergpt/ root with:
    streamlit run ui/app.py

Flow:
  1. Founder types in a raw startup idea.
  2. We call agents.orchestrator.run_pipeline(idea), which runs the
     4-agent sequential pipeline (research -> competitor -> marketing
     -> finance) and returns a dict of section -> markdown text.
  3. Results render as tabs, plus a single "download full report"
     button built from tools/report_generator.py.

This file intentionally contains zero agent logic — it only calls
into agents/orchestrator.py and tools/report_generator.py, so the UI
and the CLI (cli.py) stay in sync automatically.
"""

import asyncio
import os
import sys

import streamlit as st
from dotenv import load_dotenv

# Allow running `streamlit run ui/app.py` directly from the ui/ folder
# by making sure the foundergpt/ root is on the path.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

load_dotenv()

from agents.orchestrator import run_pipeline, SECTION_TITLES  # noqa: E402
from tools.report_generator import build_report  # noqa: E402

st.set_page_config(page_title="FounderGPT", page_icon="🚀", layout="wide")

st.title("🚀 FounderGPT")
st.caption(
    "Turn a raw startup idea into a research-backed blueprint: market "
    "research, competitor analysis, GTM + landing page copy, revenue "
    "model, MVP roadmap, and an investor pitch — generated by a 4-agent "
    "pipeline built on Google ADK + Gemini."
)

if not os.getenv("GOOGLE_API_KEY"):
    st.warning(
        "No GOOGLE_API_KEY found. Add it to a .env file in the project "
        "root before generating (see .env.example).",
        icon="⚠️",
    )

idea = st.text_input(
    "Describe your startup idea",
    placeholder="e.g. I want to build an offline UPI reliability product",
)

generate_clicked = st.button("Generate Blueprint", type="primary", disabled=not idea.strip())

if "results" not in st.session_state:
    st.session_state.results = None
    st.session_state.idea_used = None

if generate_clicked:
    with st.status("Running the agent pipeline...", expanded=True) as status:
        st.write("🔎 Research agent gathering market signals...")
        st.write("🥊 Competitor agent mapping the landscape...")
        st.write("📣 Marketing agent drafting GTM + landing page...")
        st.write("💰 Finance agent building the revenue model & pitch...")
        try:
            results = asyncio.run(run_pipeline(idea))
            st.session_state.results = results
            st.session_state.idea_used = idea
            status.update(label="Blueprint ready!", state="complete")
        except Exception as e:
            status.update(label="Something went wrong", state="error")
            st.error(f"Pipeline failed: {e}")

if st.session_state.results:
    results = st.session_state.results
    tabs = st.tabs(list(SECTION_TITLES.values()))
    for tab, key in zip(tabs, SECTION_TITLES.keys()):
        with tab:
            content = results.get(key, "")
            if content:
                st.markdown(content)
            else:
                st.info("This agent didn't return content.")

    st.divider()
    full_report = build_report(st.session_state.idea_used, results)
    st.download_button(
        label="⬇️ Download Full Report (Markdown)",
        data=full_report,
        file_name="foundergpt_blueprint.md",
        mime="text/markdown",
    )
